// <auto-generated />
using System;
using BackEnd.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(DBTestBGContext))]
    [Migration("20230717104314_set_more_data")]
    partial class set_more_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.DataBase.Entity.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6511),
                            Deleted = false,
                            Description = "Actor famoso de Hollywood",
                            Name = "Brad Pitt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6521),
                            Deleted = false,
                            Description = "Actor destacado en múltiples películas",
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6522),
                            Deleted = false,
                            Description = "Actriz talentosa y versátil",
                            Name = "Meryl Streep"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6523),
                            Deleted = false,
                            Description = "Actor icónico de la industria cinematográfica",
                            Name = "Tom Hanks"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6523),
                            Deleted = false,
                            Description = "Actriz conocida por su papel en películas de superhéroes",
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6524),
                            Deleted = false,
                            Description = "Actor reconocido por interpretar a Iron Man",
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6525),
                            Deleted = false,
                            Description = "Actriz ganadora de premios y reconocida por Los juegos del hambre",
                            Name = "Jennifer Lawrence"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6525),
                            Deleted = false,
                            Description = "Actor destacado en películas dramáticas",
                            Name = "Denzel Washington"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6526),
                            Deleted = false,
                            Description = "Actriz talentosa y versátil",
                            Name = "Emma Stone"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6527),
                            Deleted = false,
                            Description = "Actor conocido por su interpretación de personajes excéntricos",
                            Name = "Johnny Depp"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6528),
                            Deleted = false,
                            Description = "Actriz versátil y ganadora del premio de la Academia",
                            Name = "Anne Hathaway"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6528),
                            Deleted = false,
                            Description = "Actor australiano conocido por interpretar a Thor",
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6529),
                            Deleted = false,
                            Description = "Actriz versátil y ganadora del premio de la Academia",
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6530),
                            Deleted = false,
                            Description = "Actor conocido por películas como El lado bueno de las cosas",
                            Name = "Bradley Cooper"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6530),
                            Deleted = false,
                            Description = "Actriz y activista conocida por su papel en Tomb Raider",
                            Name = "Angelina Jolie"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6531),
                            Deleted = false,
                            Description = "Actordestacado en películas de acción",
                            Name = "Keanu Reeves"
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6629),
                            Deleted = false,
                            Description = "+18"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6631),
                            Deleted = false,
                            Description = "+21"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6632),
                            Deleted = false,
                            Description = "+12"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6633),
                            Deleted = false,
                            Description = "+9"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6633),
                            Deleted = false,
                            Description = "Todo público"
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6646),
                            Deleted = false,
                            Description = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6647),
                            Deleted = false,
                            Description = "Aventura"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6648),
                            Deleted = false,
                            Description = "Comedia"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6649),
                            Deleted = false,
                            Description = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6649),
                            Deleted = false,
                            Description = "Suspenso"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6650),
                            Deleted = false,
                            Description = "Terror"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6651),
                            Deleted = false,
                            Description = "Ciencia ficción"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6651),
                            Deleted = false,
                            Description = "Animación"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6652),
                            Deleted = false,
                            Description = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6653),
                            Deleted = false,
                            Description = "Documental"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6653),
                            Deleted = false,
                            Description = "Fantasía"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6654),
                            Deleted = false,
                            Description = "Histórico"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6655),
                            Deleted = false,
                            Description = "Misterio"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6655),
                            Deleted = false,
                            Description = "Western"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6656),
                            Deleted = false,
                            Description = "Musical"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6657),
                            Deleted = false,
                            Description = "Deporte"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6657),
                            Deleted = false,
                            Description = "Guerra"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6658),
                            Deleted = false,
                            Description = "Crimen"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6659),
                            Deleted = false,
                            Description = "Aventura espacial"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6661),
                            Deleted = false,
                            Description = "Superhéroes"
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6678),
                            Deleted = false,
                            LongDescription = "Un exasesino busca venganza después de que le roban lo más preciado que le quedaba: su perro.",
                            Name = "John Wick",
                            ShortDescription = "Un hombre en busca de justicia en un mundo de asesinos.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6680),
                            Deleted = false,
                            LongDescription = "El agente Ethan Hunt se enfrenta a su misión más peligrosa hasta ahora cuando una operación sale mal y pone en peligro a millones de personas.",
                            Name = "Mission: Impossible - Fallout",
                            ShortDescription = "La misión imposible más intensa y emocionante.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6681),
                            Deleted = false,
                            LongDescription = "Los Vengadores y sus aliados se unen para luchar contra el poderoso Thanos y evitar que obtenga las gemas del infinito y destruya el universo.",
                            Name = "Avengers: Infinity War",
                            ShortDescription = "La batalla definitiva por el destino del universo.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6682),
                            Deleted = false,
                            LongDescription = "Batman se enfrenta al Joker, un criminal psicótico que amenaza con sumir Gotham City en el caos y la anarquía.",
                            Name = "The Dark Knight",
                            ShortDescription = "El caballero oscuro contra el príncipe payaso del crimen.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6683),
                            Deleted = false,
                            LongDescription = "En un mundo postapocalíptico, Max Rockatansky y Furiosa se unen para",
                            Name = "Mad Max: Fury Road",
                            ShortDescription = "La película muestra una historia deslumbrante.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6684),
                            Deleted = false,
                            LongDescription = "Un policía de Nueva York se enfrenta a un grupo de terroristas en un rascacielos en Los Ángeles.",
                            Name = "Die Hard",
                            ShortDescription = "El héroe que salvará la Navidad.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6685),
                            Deleted = false,
                            LongDescription = "Un cyborg asesino del futuro es enviado al pasado para matar a una mujer cuyo hijo se convertirá en la única esperanza de la humanidad contra las máquinas.",
                            Name = "The Terminator",
                            ShortDescription = "El futuro está en juego.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6687),
                            Deleted = false,
                            LongDescription = "El arqueólogo y aventurero Indiana Jones se embarca en una peligrosa misión para encontrar el Arca de la Alianza antes que los nazis.",
                            Name = "Indiana Jones: Raiders of the Lost Ark",
                            ShortDescription = "La aventura comienza.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6687),
                            Deleted = false,
                            LongDescription = "Un parque temático lleno de dinosaurios vivos se convierte en una pesadilla cuando las criaturas escapan y comienzan a causar estragos.",
                            Name = "Jurassic Park",
                            ShortDescription = "La maravilla de la prehistoria en la actualidad.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6688),
                            Deleted = false,
                            LongDescription = "Un hobbit llamado Frodo se embarca en una épica aventura para destruir un anillo mágico y salvar la Tierra Media de la oscuridad.",
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            ShortDescription = "El comienzo de una gran guerra.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6689),
                            Deleted = false,
                            LongDescription = "El Capitán Jack Sparrow se embarca en una aventura para recuperar su barco robado y salvar a una gobernadora secuestrada de una maldición pirata.",
                            Name = "Pirates of the Caribbean: The Curse of the Black Pearl",
                            ShortDescription = "La vida de un pirata nunca ha sido tan divertida.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6690),
                            Deleted = false,
                            LongDescription = "Un grupo de amigos se embarca en una aventura en busca de un tesoro perdido para salvar sus hogares de ser demolidos.",
                            Name = "The Goonies",
                            ShortDescription = "La pandilla más divertida en busca de aventuras.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6691),
                            Deleted = false,
                            LongDescription = "Un aventurero y una arqueóloga luchan contra una antigua maldición y enfrentan criaturas sobrenaturales mientras intentan salvar al mundo.",
                            Name = "The Mummy",
                            ShortDescription = "La aventura más emocionante en Egipto.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6726),
                            Deleted = false,
                            LongDescription = "Una niña es poseída por una entidad demoníaca y un sacerdote lucha por salvar su alma.",
                            Name = "The Exorcist",
                            ShortDescription = "El clásico del terror que te hará temblar.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6727),
                            Deleted = false,
                            LongDescription = "Un escritor y su familia se mudan a un hotel aislado donde ocurren sucesos aterradores.",
                            Name = "The Shining",
                            ShortDescription = "Una historia de terror psicológico que te mantendrá en vilo.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6728),
                            Deleted = false,
                            LongDescription = "Un asesino enmascarado aterroriza a una pequeña ciudad en la noche de Halloween.",
                            Name = "Halloween",
                            ShortDescription = "Un clásico del cine slasher que te hará saltar de miedo.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6728),
                            Deleted = false,
                            LongDescription = "Un grupo de adolescentes es perseguido en sus sueños por un asesino de pesadilla.",
                            Name = "A Nightmare on Elm Street",
                            ShortDescription = "No podrás dormir tranquilo después de ver esta película.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6729),
                            Deleted = false,
                            LongDescription = "Una pareja de investigadores paranormales ayuda a una familia a enfrentarse a una presencia malévola en su casa.",
                            Name = "The Conjuring",
                            ShortDescription = "Una historia basada en hechos reales que te dejará sin aliento.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6730),
                            Deleted = false,
                            LongDescription = "Un grupo de niños se enfrenta a un aterrador payaso que aterroriza su ciudad.",
                            Name = "It",
                            ShortDescription = "El regreso del payaso más aterrador del cine.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6731),
                            Deleted = false,
                            LongDescription = "Un joven negro visita la casa de la familia de su novia blanca y descubre un oscuro secreto.",
                            Name = "Get Out",
                            ShortDescription = "Un thriller psicológico que te mantendrá en vilo hasta el final.",
                            Url = "https://portadascreativas.com/wp-content/uploads/Matrix.jpg"
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6798),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6799),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 4,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6799),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6800),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 7,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6801),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 8,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6801),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 9,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6802),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 10,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6802),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 11,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6803),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6804),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 12,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6804),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6805),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 15,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6806),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 14,
                            ActorId = 14,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6806),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 15,
                            ActorId = 11,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6807),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 16,
                            ActorId = 8,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6807),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 17,
                            ActorId = 9,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6808),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 18,
                            ActorId = 13,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6809),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 19,
                            ActorId = 5,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6809),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 20,
                            ActorId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6810),
                            Deleted = false
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6771),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6772),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6773),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6773),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6774),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6775),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6775),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6778),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6778),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6779),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6780),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6780),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6781),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6781),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6782),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 16,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6783),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 17,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6783),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 18,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6784),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 19,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6784),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 20,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6785),
                            Deleted = false
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6744),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6745),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6747),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6748),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6748),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6749),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6750),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6750),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6751),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6752),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6752),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6753),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6754),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6754),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6755),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6756),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6756),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6757),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6758),
                            Deleted = false
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 6,
                            CreatedAt = new DateTime(2023, 7, 17, 5, 43, 14, 672, DateTimeKind.Local).AddTicks(6758),
                            Deleted = false
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieActor", b =>
                {
                    b.HasOne("BackEnd.DataBase.Entity.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.DataBase.Entity.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieCategory", b =>
                {
                    b.HasOne("BackEnd.DataBase.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.DataBase.Entity.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieGenre", b =>
                {
                    b.HasOne("BackEnd.DataBase.Entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.DataBase.Entity.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieCategories");

                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
