// <auto-generated />
using System;
using BackEnd.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(DBTestBGContext))]
    [Migration("20230716232751_fix-column-created")]
    partial class fixcolumncreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.DataBase.Entity.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(294),
                            Deleted = false,
                            Description = "Actor famoso de Hollywood",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brad Pitt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(304),
                            Deleted = false,
                            Description = "Actor destacado en múltiples películas",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(305),
                            Deleted = false,
                            Description = "Actriz talentosa y versátil",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Meryl Streep"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(305),
                            Deleted = false,
                            Description = "Actor icónico de la industria cinematográfica",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tom Hanks"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(306),
                            Deleted = false,
                            Description = "Actriz conocida por su papel en películas de superhéroes",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(307),
                            Deleted = false,
                            Description = "Actor reconocido por interpretar a Iron Man",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(308),
                            Deleted = false,
                            Description = "Actriz ganadora de premios y reconocida por Los juegos del hambre",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jennifer Lawrence"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(308),
                            Deleted = false,
                            Description = "Actor destacado en películas dramáticas",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Denzel Washington"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(309),
                            Deleted = false,
                            Description = "Actriz talentosa y versátil",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emma Stone"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(310),
                            Deleted = false,
                            Description = "Actor conocido por su interpretación de personajes excéntricos",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Johnny Depp"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(311),
                            Deleted = false,
                            Description = "Actriz versátil y ganadora del premio de la Academia",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anne Hathaway"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(311),
                            Deleted = false,
                            Description = "Actor australiano conocido por interpretar a Thor",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(312),
                            Deleted = false,
                            Description = "Actriz versátil y ganadora del premio de la Academia",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(313),
                            Deleted = false,
                            Description = "Actor conocido por películas como El lado bueno de las cosas",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bradley Cooper"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(313),
                            Deleted = false,
                            Description = "Actriz y activista conocida por su papel en Tomb Raider",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Angelina Jolie"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(314),
                            Deleted = false,
                            Description = "Actordestacado en películas de acción",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Keanu Reeves"
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(414),
                            Deleted = false,
                            Description = "+18",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(415),
                            Deleted = false,
                            Description = "+21",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(416),
                            Deleted = false,
                            Description = "+12",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(417),
                            Deleted = false,
                            Description = "+9",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(417),
                            Deleted = false,
                            Description = "Todo público",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(432),
                            Deleted = false,
                            Description = "Acción",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(433),
                            Deleted = false,
                            Description = "Aventura",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(434),
                            Deleted = false,
                            Description = "Comedia",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(435),
                            Deleted = false,
                            Description = "Drama",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(435),
                            Deleted = false,
                            Description = "Suspenso",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(436),
                            Deleted = false,
                            Description = "Terror",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(437),
                            Deleted = false,
                            Description = "Ciencia ficción",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(437),
                            Deleted = false,
                            Description = "Animación",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(438),
                            Deleted = false,
                            Description = "Romance",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(439),
                            Deleted = false,
                            Description = "Documental",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(439),
                            Deleted = false,
                            Description = "Fantasía",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(440),
                            Deleted = false,
                            Description = "Histórico",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(440),
                            Deleted = false,
                            Description = "Misterio",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(441),
                            Deleted = false,
                            Description = "Western",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(442),
                            Deleted = false,
                            Description = "Musical",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(442),
                            Deleted = false,
                            Description = "Deporte",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(443),
                            Deleted = false,
                            Description = "Guerra",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(444),
                            Deleted = false,
                            Description = "Crimen",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(444),
                            Deleted = false,
                            Description = "Aventura espacial",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(445),
                            Deleted = false,
                            Description = "Superhéroes",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(460),
                            Deleted = false,
                            LongDescription = "Un exasesino busca venganza después de que le roban lo más preciado que le quedaba: su perro.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Wick",
                            ShortDescription = "Un hombre en busca de justicia en un mundo de asesinos.",
                            Url = "https://example.com/john-wick.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(461),
                            Deleted = false,
                            LongDescription = "El agente Ethan Hunt se enfrenta a su misión más peligrosa hasta ahora cuando una operación sale mal y pone en peligro a millones de personas.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mission: Impossible - Fallout",
                            ShortDescription = "La misión imposible más intensa y emocionante.",
                            Url = "https://example.com/mission-impossible-fallout.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(463),
                            Deleted = false,
                            LongDescription = "Los Vengadores y sus aliados se unen para luchar contra el poderoso Thanos y evitar que obtenga las gemas del infinito y destruya el universo.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Avengers: Infinity War",
                            ShortDescription = "La batalla definitiva por el destino del universo.",
                            Url = "https://example.com/avengers-infinity-war.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(501),
                            Deleted = false,
                            LongDescription = "Batman se enfrenta al Joker, un criminal psicótico que amenaza con sumir Gotham City en el caos y la anarquía.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Dark Knight",
                            ShortDescription = "El caballero oscuro contra el príncipe payaso del crimen.",
                            Url = "https://example.com/the-dark-knight.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(502),
                            Deleted = false,
                            LongDescription = "En un mundo postapocalíptico, Max Rockatansky y Furiosa se unen para",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mad Max: Fury Road",
                            ShortDescription = "La película muestra una historia deslumbrante.",
                            Url = "https://example.com/mad-max-fury-road.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(503),
                            Deleted = false,
                            LongDescription = "Un policía de Nueva York se enfrenta a un grupo de terroristas en un rascacielos en Los Ángeles.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Die Hard",
                            ShortDescription = "El héroe que salvará la Navidad.",
                            Url = "https://example.com/die-hard.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(504),
                            Deleted = false,
                            LongDescription = "Un cyborg asesino del futuro es enviado al pasado para matar a una mujer cuyo hijo se convertirá en la única esperanza de la humanidad contra las máquinas.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Terminator",
                            ShortDescription = "El futuro está en juego.",
                            Url = "https://example.com/the-terminator.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(505),
                            Deleted = false,
                            LongDescription = "El arqueólogo y aventurero Indiana Jones se embarca en una peligrosa misión para encontrar el Arca de la Alianza antes que los nazis.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Indiana Jones: Raiders of the Lost Ark",
                            ShortDescription = "La aventura comienza.",
                            Url = "https://example.com/indiana-jones-raiders-of-the-lost-ark.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(506),
                            Deleted = false,
                            LongDescription = "Un parque temático lleno de dinosaurios vivos se convierte en una pesadilla cuando las criaturas escapan y comienzan a causar estragos.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jurassic Park",
                            ShortDescription = "La maravilla de la prehistoria en la actualidad.",
                            Url = "https://example.com/jurassic-park.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(506),
                            Deleted = false,
                            LongDescription = "Un hobbit llamado Frodo se embarca en una épica aventura para destruir un anillo mágico y salvar la Tierra Media de la oscuridad.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            ShortDescription = "El comienzo de una gran guerra.",
                            Url = "https://example.com/the-lord-of-the-rings-the-fellowship-of-the-ring.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(508),
                            Deleted = false,
                            LongDescription = "El Capitán Jack Sparrow se embarca en una aventura para recuperar su barco robado y salvar a una gobernadora secuestrada de una maldición pirata.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pirates of the Caribbean: The Curse of the Black Pearl",
                            ShortDescription = "La vida de un pirata nunca ha sido tan divertida.",
                            Url = "https://example.com/pirates-of-the-caribbean-the-curse-of-the-black-pearl.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(508),
                            Deleted = false,
                            LongDescription = "Un grupo de amigos se embarca en una aventura en busca de un tesoro perdido para salvar sus hogares de ser demolidos.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Goonies",
                            ShortDescription = "La pandilla más divertida en busca de aventuras.",
                            Url = "https://example.com/the-goonies.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(509),
                            Deleted = false,
                            LongDescription = "Un aventurero y una arqueóloga luchan contra una antigua maldición y enfrentan criaturas sobrenaturales mientras intentan salvar al mundo.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Mummy",
                            ShortDescription = "La aventura más emocionante en Egipto.",
                            Url = "https://example.com/the-mummy.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(510),
                            Deleted = false,
                            LongDescription = "Una niña es poseída por una entidad demoníaca y un sacerdote lucha por salvar su alma.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Exorcist",
                            ShortDescription = "El clásico del terror que te hará temblar.",
                            Url = "https://example.com/the-exorcist.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(512),
                            Deleted = false,
                            LongDescription = "Un escritor y su familia se mudan a un hotel aislado donde ocurren sucesos aterradores.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Shining",
                            ShortDescription = "Una historia de terror psicológico que te mantendrá en vilo.",
                            Url = "https://example.com/the-shining.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(513),
                            Deleted = false,
                            LongDescription = "Un asesino enmascarado aterroriza a una pequeña ciudad en la noche de Halloween.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Halloween",
                            ShortDescription = "Un clásico del cine slasher que te hará saltar de miedo.",
                            Url = "https://example.com/halloween.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(514),
                            Deleted = false,
                            LongDescription = "Un grupo de adolescentes es perseguido en sus sueños por un asesino de pesadilla.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "A Nightmare on Elm Street",
                            ShortDescription = "No podrás dormir tranquilo después de ver esta película.",
                            Url = "https://example.com/nightmare-on-elm-street.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(514),
                            Deleted = false,
                            LongDescription = "Una pareja de investigadores paranormales ayuda a una familia a enfrentarse a una presencia malévola en su casa.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Conjuring",
                            ShortDescription = "Una historia basada en hechos reales que te dejará sin aliento.",
                            Url = "https://example.com/the-conjuring.jpg"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(515),
                            Deleted = false,
                            LongDescription = "Un grupo de niños se enfrenta a un aterrador payaso que aterroriza su ciudad.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "It",
                            ShortDescription = "El regreso del payaso más aterrador del cine.",
                            Url = "https://example.com/it.jpg"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(516),
                            Deleted = false,
                            LongDescription = "Un joven negro visita la casa de la familia de su novia blanca y descubre un oscuro secreto.",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Get Out",
                            ShortDescription = "Un thriller psicológico que te mantendrá en vilo hasta el final.",
                            Url = "https://example.com/get-out.jpg"
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(571),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(572),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(572),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(573),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(574),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(574),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(575),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(576),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(576),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(577),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(577),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(578),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 16,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(578),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(551),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(552),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(553),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(553),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(554),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(555),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(555),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(556),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(557),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(557),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(558),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 12,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(558),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(559),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(531),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(532),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(533),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(533),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(534),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(535),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(535),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(536),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(537),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(537),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(538),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(539),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 1,
                            CreatedAt = new DateTime(2023, 7, 16, 18, 27, 51, 361, DateTimeKind.Local).AddTicks(539),
                            Deleted = false,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieActor", b =>
                {
                    b.HasOne("BackEnd.DataBase.Entity.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.DataBase.Entity.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieCategory", b =>
                {
                    b.HasOne("BackEnd.DataBase.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.DataBase.Entity.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.MovieGenre", b =>
                {
                    b.HasOne("BackEnd.DataBase.Entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.DataBase.Entity.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BackEnd.DataBase.Entity.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieCategories");

                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
